on:
  push:
    branches:
      - master

jobs:
  CICD:
    name: "CI/CD"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: npm ci
        run: |
          npm ci
      
      - name: Test
        run: |
          npm run test

      - name: build
        run: |
          npm run build

      # Un Comment for cdk deployment
      # - name: cdk deploy
      #   uses: youyo/aws-cdk-github-actions@v2
      #   with:
      #     cdk_subcommand: 'deploy'
      #     cdk_args: '--require-approval never'
      #     actions_comment: false
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: 'us-west-2'
